export interface Car {
    name:string,
    description:string,
    attributes:[
        {
            traitType:string,
            value:string
        },
        {
            traitType:string,
            value:string
        },
        {
            traitType:string,
            value:string
        },
        {
            traitType:string,
            value:string
        }
    ]
    image:string
}